name: magurotuna
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      - name: "Reference: generate types"
        working-directory: "reference_gen"
        run: deno task types
  
      - name: "Reference: generate docs"
        working-directory: "reference_gen"
        run: deno task doc

      - name: Build
        run: deno task build
    
      - name: Collect assets to be uploaded
        run: deno run --allow-read magurotuna.ts
